set-option -g default-shell /usr/bin/fish
set-option -g default-command /usr/bin/fish

bind c new-window -c "#{pane_current_path}"

bind-key -n M-J previous-window
bind-key -n M-: next-window

set-option -g @move_mode 0

bind-key m if-shell '[ "$(tmux show-option -gv @move_mode)" = "1" ]' \
    'set-option -g @move_mode 0; display-message "Move mode OFF"' \
    'set-option -g @move_mode 1; display-message "Move mode ON"'

bind-key -n M-J if-shell '[ "$(tmux show-option -gv @move_mode)" = "1" ]' \
    'swap-window -t -1; select-window -t -1' \
    'previous-window'

bind-key -n M-: if-shell '[ "$(tmux show-option -gv @move_mode)" = "1" ]' \
    'swap-window -t +1; select-window -t +1' \
    'next-window'

set -sg escape-time 0
set -g mode-keys vi
